### PR TITLE
Tools for development

### PR DESCRIPTION
**Pull request by timretout**
The first three of these changes make it easier to run the site locally; adding a Gemfile and instructions for running a local development environment, and continuous integration via Travis CI for validating HTML and links.

The fourth change updates the link to isdebianreproducibleyet.com, which was caught by the test for https links.

### CODE REVIEW

**Comment by lamby** [comment]
Happy to merge but the readme.md duplicates the index.md too much for my liking; it will surely get out of date? :)

**Comment by timretout** [comment]
@lamby Hmm, I could trim it back to just build instructions? I mindlessly copied the rest based on a template of what should go in a README. ;)

**Comment by timretout** [comment]
@lamby I've no idea of the GitHub pull request etiquette w.r.t. squashing changes, so I've just pushed another commit while I go and search whether that's the right thing

**Comment by lamby** [comment]
Force-pushig to PRs is fine for me. Looking again... I'd just drop the README, it's pretty entropyless for anyone used to a `gh-pages` pages or Jekyll. :)

**Comment by timretout** [comment]
I've dropped it because this is not the hill I'm planning to die on!

**Comment by lamby** [comment]
thanks!

**Pull request merged**
