### PR TITLE
Add missing closing </div>

### PR DESCRIPTION
**Pull request by jorgesumle**

### CODE REVIEW

**Comment by lamby** [comment]
Thanks! How did you find this?

**Comment by jorgesumle** [comment]
Looking at the source code

**Comment by lamby** [comment]
I mean, was it causing a rendering issue for you?

**Comment by jorgesumle** [comment]
Sorry, I didn't explain myself very well. I was just having a quick look at the HTML and Tor Browser shows HTML syntax errors in red, so they become visible when you press <kbd>C-U</kbd> to show the source code.

**Pull request merged**
