### PR TITLE
Use jekyll layout and markdown

### PR DESCRIPTION
**Pull request by timretout**
(Not sure if you'll like this)

When trying previously to redraft the text of the site, I've ended up spending far too much time worrying about formatting and whitespace, I think in part because the site is written in plain HTML.

These commits move most of the boilerplate header/footer info into the layout, and uses markdown for the main article text. (Plus a one-character fix from #10 to avoid conflicting with that pull request.)

Pros:
- Easier to edit article text in future (I think)
- Headings now get id attributes for free

Cons:
- Fairly large change?
- Jekyll-specific markdown hacks to preserve section heading CSS classes
- More difficult to preview site without jekyll (though this was never really possible imho)

On balance, I'm sending the pull request anyway.  I think my goal in this PR and #10 is to make "patches welcome" more meaningful, by reducing the friction to making changes to the text.

### CODE REVIEW

**Comment by lamby** [comment]
Looks good. I'd just also now use  `baseurl` to construct relative URLs and now that we are using `.md` use literal — over mdash (and the other HTML entities). :)

**Comment by timretout** [comment]
OK, this now puts as much as possible into markdown or unicode rather than HTML - still left with smal/sup/tt tags.  I didn't quite get the reference about baseurl, because afaik relative URLs just work?

As a followup I'm tempted to copy the "section-heading" CSS to just apply it to all h2/h3s, and similarly avoid the "ref" class on sup anchors.  Either way this Markdown is looking pretty editable.

**Comment by lamby** [comment]
> I didn't quite get the reference about baseurl, because afaik relative URLs just work?

Best — or at least standard — practice with Jekyll is not to use relative URLs but rather `{{ "/foo/" | prepend: site.baseurl }}`. :)

**Comment by timretout** [comment]
> Best — or at least standard — practice with Jekyll is not to use relative URLs but rather `{{ "/foo/" | prepend: site.baseurl }}`. :)

Eh, brushing up on my jekyll-fu now to understand this: the "relative_url" filter would be the latest way to do this, and would be relevant if the baseurl is set to a non-root path (e.g. baseurl = "/apt-https" or similar) - could be applied to the <link> tags referencing the CSS, for example, to make it possible to host a copy on GitHub project pages, say.  But I don't think there's any point for the footnote links, since they'll work whatever baseurl is set to.

I'll revise this PR later to handle this and the CSS changes I proposed.

**Comment by timretout** [comment]
Right, the most exciting change in this version is to use the footnotes support in Kramdown, with a touch of CSS to keep the wikipedia-like styling.  This does mean that the anchor ids change incompatibly, but it means you can reorder the text easily in the future, and get links back to the point in the text which referred you.

The em-dashes are supported via Kramdown's syntax too.

The section-header class is replaced with CSS applied to the h2, h3 elements, and I tidied up the disclaimer styling slightly.

**Comment by lamby** [comment]
Merging, thanks!

**Pull request merged**
