### PR TITLE
First try at suggesting APT users use TLS

### PR DESCRIPTION
**Pull request by ice799**
Using plain text HTTP GPG signed APT repositories leaves users vulnerable to several serious security vulnerabilities. Also, this website seems to suggests that GPG signatures of Debian packages are used by major distributions -- this is not the case.

I've tried to modify the text a bit to reflect this. FWIW, I think probably you could just put a banner at the top that says something "Always use HTTPS when connecting to an APT repository, no exceptions" and then follow with the technical information.

Hopefully this PR can help serve as a starting point for bringing the information presented on this website up to date to help make everyone safer.

### CODE REVIEW

**Comment by ice799** [comment]
This PR is in response to @lamby's request for a draft in https://github.com/lamby/whydoesaptnotusehttps.com/issues/4.

**Comment by lamby** [comment]
So, hm, I'm a little hesitant to merge this in its current state given that it links to a commercial/paid-for/proprietary service.

**Comment by ice799** [comment]
Feel free to modify it how you see fit; it links to a blog post which explains the vulnerabilities, how this affects open source tools like `reprepro` and `dpkg`, and is freely accessible/readable without any payment required.

**Comment by lamby** [comment]
Re-reading this PR, I'm afraid that I don't agree with its narrative/story and tone even though I don't necessary disagree with anything specific that is suggested - it is saying/suggesting things like "should" etc. etc. instead of describing the current APT world as it stands. Admittedly, the shilling of PackageCloud blog post ("helpful"..) does not help, alas.. :(

**Pull request closed without merging**
